# These are supported funding model platforms

github:
patreon: A_EDev
open_collective:
ko_fi:
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee:
thanks_dev:

# Link directly to the "Support & Donations" section of the README.
custom: ["https://github.com/A-EDev/Flow#support--donations"]
