import type { AudioTrack, CaptionTrack, StreamVariant } from "../../types/video";
import type { PlaybackRate } from "../../store/usePlayerStore";
import { codecRank } from "../codecPreference";

export const DEFAULT_PLAYBACK_RATES: PlaybackRate[] = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2];

export function normalizePlaybackRate(value: string | number, fallback: PlaybackRate = 1): PlaybackRate {
  const parsed = typeof value === "number" ? value : Number(value);
  if (!Number.isFinite(parsed)) return fallback;
  return Math.min(4, Math.max(0.25, Math.round(parsed * 100) / 100));
}

export function formatPlaybackRate(value: PlaybackRate): string {
  const normalized = normalizePlaybackRate(value);
  return Number.isInteger(normalized) ? `${normalized}.0` : String(normalized);
}

export function parseCustomSpeedPresets(rawValue: string, enabled: boolean): PlaybackRate[] {
  if (!enabled) return DEFAULT_PLAYBACK_RATES;

  const parsed = rawValue
    .split(",")
    .map((value) => value.trim())
    .filter(Boolean)
    .map((value) => normalizePlaybackRate(value, Number.NaN));

  const unique = Array.from(new Set(parsed.filter(Number.isFinite)));
  if (unique.length === 0) return DEFAULT_PLAYBACK_RATES;

  return unique.sort((left, right) => left - right);
}

export function selectPreferredCaptionId(
  captions: CaptionTrack[],
  preferredLanguage: string,
): string | null {
  const normalizedLanguage = preferredLanguage.trim().toLowerCase();
  if (!normalizedLanguage || captions.length === 0) return null;

  const normalizedTrackLanguage = (caption: CaptionTrack) => caption.languageCode.trim().toLowerCase();
  const exactManual = captions.find(
    (caption) => normalizedTrackLanguage(caption) === normalizedLanguage && !caption.isAutoGenerated,
  );
  if (exactManual) return exactManual.id;

  const exactAny = captions.find((caption) => normalizedTrackLanguage(caption) === normalizedLanguage);
  if (exactAny) return exactAny.id;

  const prefixManual = captions.find((caption) => {
    const trackLanguage = normalizedTrackLanguage(caption);
    return (trackLanguage.startsWith(`${normalizedLanguage}-`) || normalizedLanguage.startsWith(`${trackLanguage}-`))
      && !caption.isAutoGenerated;
  });
  if (prefixManual) return prefixManual.id;

  const prefixAny = captions.find((caption) => {
    const trackLanguage = normalizedTrackLanguage(caption);
    return trackLanguage.startsWith(`${normalizedLanguage}-`) || normalizedLanguage.startsWith(`${trackLanguage}-`);
  });
  if (prefixAny) return prefixAny.id;

  return captions.find((caption) => !caption.isAutoGenerated)?.id ?? captions[0]?.id ?? null;
}

export function selectPreferredAudioTrackId(
  tracks: AudioTrack[],
  preferredLanguage: string,
): string | null {
  tracks = tracks.filter((track) => track.available !== false);
  const normalizedLanguage = preferredLanguage.trim().toLowerCase();
  if (!normalizedLanguage || normalizedLanguage === "original" || tracks.length === 0) return null;

  const normalizedTrackLanguage = (track: AudioTrack) => (track.languageCode || "").trim().toLowerCase();
  const exact = tracks.find((track) => normalizedTrackLanguage(track) === normalizedLanguage);
  if (exact) return exact.id;

  const prefix = tracks.find((track) => {
    const trackLanguage = normalizedTrackLanguage(track);
    return trackLanguage.startsWith(`${normalizedLanguage}-`) || normalizedLanguage.startsWith(`${trackLanguage}-`);
  });

  return prefix?.id ?? null;
}

export function videoCodecLabel(mimeType: string | null | undefined): string | null {
  const value = (mimeType || "").toLowerCase();
  if (value.includes("av01") || value.includes("av1")) return "AV1";
  if (value.includes("vp09") || value.includes("vp9")) return "VP9";
  if (value.includes("vp08") || value.includes("vp8")) return "VP8";
  if (value.includes("hev1") || value.includes("hvc1") || value.includes("hevc") || value.includes("h265"))
    return "HEVC";
  if (value.includes("avc1") || value.includes("avc3") || value.includes("h264")) return "H.264";
  return null;
}

const codecMatches = (mimeType: string | null | undefined, preferredCodec: string) => {
  const normalizedMime = (mimeType || "").toLowerCase();
  switch (preferredCodec) {
    case "H.264":
      return normalizedMime.includes("avc1") || normalizedMime.includes("avc3") || normalizedMime.includes("h264");
    case "VP9":
      return normalizedMime.includes("vp9") || normalizedMime.includes("vp09");
    case "AV1":
      return normalizedMime.includes("av01") || normalizedMime.includes("av1");
    default:
      return true;
  }
};

const qualityHeight = (quality: string) => {
  if (quality === "Auto") return null;
  const parsed = Number(quality.replace(/p$/i, ""));
  return Number.isFinite(parsed) ? parsed : null;
};

export function filterByPreferredCodec(
  variants: StreamVariant[],
  preferredCodec: string,
): StreamVariant[] {
  if (preferredCodec === "Auto") return variants;
  const matching = variants.filter((variant) => codecMatches(variant.mimeType, preferredCodec));
  return matching.length > 0 ? matching : variants;
}

export function selectPreferredStreamVariant(
  variants: StreamVariant[],
  preferredQuality: string,
  preferredCodec: string,
  canUseAdaptive: boolean,
): StreamVariant | null {
  const targetHeight = qualityHeight(preferredQuality);
  if (!targetHeight) return null;

  const playable = variants.filter((variant) => variant.isPlayable && (variant.hasAudio || canUseAdaptive));
  if (playable.length === 0) return null;

  const candidates = filterByPreferredCodec(playable, preferredCodec);

  const belowOrEqual = candidates
    .filter((variant) => (variant.height || 0) <= targetHeight)
    .sort(
      (left, right) =>
        (right.height || 0) - (left.height || 0) ||
        codecRank(left.mimeType) - codecRank(right.mimeType) ||
        (right.bitrate || 0) - (left.bitrate || 0),
    );
  if (belowOrEqual[0]) return belowOrEqual[0];

  return [...candidates].sort(
    (left, right) =>
      Math.abs((left.height || 0) - targetHeight) - Math.abs((right.height || 0) - targetHeight) ||
      codecRank(left.mimeType) - codecRank(right.mimeType),
  )[0] ?? null;
}
