//! Payload cryptography for Flow Local Sync (`FLOW-SYNC/1`).
//!
//! Security model: the WebSocket
//! transport is plaintext; the **payload** is end-to-end encrypted with AES-256-GCM. The master
//! key travels out-of-band through the QR code (camera), never the network.
//!
//! Key facts the Android implementation must match byte-for-byte:
//! * **Master secret**: 32 random bytes (CSPRNG). **Session id**: 16 random bytes (also the HKDF
//!   salt; shipped in the QR).
//! * **Directional keys** via HKDF-SHA256 with these exact `info` labels:
//!   - host→client: [`INFO_HOST_TO_CLIENT`]
//!   - client→host: [`INFO_CLIENT_TO_HOST`]
//!   The host encrypts with the host→client key; the client encrypts with the client→host key.
//!   Independent keys ⇒ independent nonce spaces.
//! * **Per-frame nonce**: 12 random bytes from the OS CSPRNG, **never reused**. The wire frame is
//!   `nonce(12) ∥ ciphertext ∥ tag(16)`.
//! * **AAD** (authenticated, not encrypted): `version(1) ∥ session_id(16) ∥ frame_type(1) ∥
//!   seq(8, big-endian)` — binds every frame to the session, its type, and its sequence number,
//!   defeating replay/reorder/truncation by an active attacker.
//! * **SAS** (Short Authentication String): the 6-digit code both sides display to confirm no
//!   MITM. `n = u32::from_be_bytes(HMAC-SHA256(master, `[`SAS_LABEL`]` ∥ session_id)[0..4]) %
//!   1_000_000`, rendered zero-padded to 6 digits.
//!
//! scope: this module is the crypto core (keys, seal/open, SAS). The protocol/transport
//! that drives sequence numbers and frame types lives in later phases.

#![allow(clippy::must_use_candidate)]

use aes_gcm::aead::{Aead, Payload};
use aes_gcm::{Aes256Gcm, KeyInit, Nonce};
use hkdf::Hkdf;
use hmac::{Hmac, Mac};
use rand::RngCore;
use rand::rngs::OsRng;
use sha2::Sha256;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::sync::PROTOCOL_VERSION;

pub const MASTER_SECRET_LEN: usize = 32;
pub const SESSION_ID_LEN: usize = 16;
pub const KEY_LEN: usize = 32;
pub const NONCE_LEN: usize = 12;
pub const TAG_LEN: usize = 16;

/// HKDF `info` label for the host→client direction key.
pub const INFO_HOST_TO_CLIENT: &[u8] = b"flow-sync/1 host->client";
/// HKDF `info` label for the client→host direction key.
pub const INFO_CLIENT_TO_HOST: &[u8] = b"flow-sync/1 client->host";
/// Domain-separation label prefix for the SAS HMAC.
pub const SAS_LABEL: &[u8] = b"flow-sync/1 sas";
/// Number of decimal digits in the SAS.
pub const SAS_DIGITS: usize = 6;

type HmacSha256 = Hmac<Sha256>;

#[derive(Debug, thiserror::Error)]
pub enum CryptoError {
    #[error("frame too short: {0} bytes (need at least {1})")]
    FrameTooShort(usize, usize),
    #[error("AEAD authentication failed (wrong key, tampered data, or wrong AAD)")]
    AuthFailed,
    #[error("invalid key length")]
    InvalidKey,
}

/// Which end of the session this device is. The host shows the QR; the client scans it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Role {
    Host,
    Client,
}

/// The 256-bit master secret. Zeroized on drop; generated by [`generate_master_secret`] or
/// recovered from the QR.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct MasterSecret([u8; MASTER_SECRET_LEN]);

impl MasterSecret {
    pub fn from_bytes(bytes: [u8; MASTER_SECRET_LEN]) -> Self {
        Self(bytes)
    }

    pub fn try_from_slice(bytes: &[u8]) -> Result<Self, CryptoError> {
        let mut arr: [u8; MASTER_SECRET_LEN] =
            bytes.try_into().map_err(|_| CryptoError::InvalidKey)?;
        let secret = Self(arr);
        // `[u8; 32]` is `Copy`, so `Self(arr)` copied the bytes — wipe this stack copy.
        arr.zeroize();
        Ok(secret)
    }

    pub fn as_bytes(&self) -> &[u8; MASTER_SECRET_LEN] {
        &self.0
    }
}

/// A 16-byte session identifier; doubles as the HKDF salt. Not secret (it is in the QR).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SessionId([u8; SESSION_ID_LEN]);

impl SessionId {
    pub fn from_bytes(bytes: [u8; SESSION_ID_LEN]) -> Self {
        Self(bytes)
    }

    pub fn try_from_slice(bytes: &[u8]) -> Result<Self, CryptoError> {
        let arr: [u8; SESSION_ID_LEN] = bytes.try_into().map_err(|_| CryptoError::InvalidKey)?;
        Ok(Self(arr))
    }

    pub fn as_bytes(&self) -> &[u8; SESSION_ID_LEN] {
        &self.0
    }
}

/// A 256-bit directional AEAD key. Zeroized on drop.
#[derive(Clone, Zeroize, ZeroizeOnDrop)]
pub struct DirectionKey([u8; KEY_LEN]);

impl DirectionKey {
    fn cipher(&self) -> Result<Aes256Gcm, CryptoError> {
        Aes256Gcm::new_from_slice(&self.0).map_err(|_| CryptoError::InvalidKey)
    }
}

/// Generate a fresh 256-bit master secret from the OS CSPRNG.
pub fn generate_master_secret() -> MasterSecret {
    let mut bytes = [0u8; MASTER_SECRET_LEN];
    OsRng.fill_bytes(&mut bytes);
    let secret = MasterSecret(bytes);
    bytes.zeroize(); // `[u8; 32]` is `Copy` — wipe the stack copy left behind.
    secret
}

/// Generate a fresh 16-byte session id from the OS CSPRNG.
pub fn generate_session_id() -> SessionId {
    let mut bytes = [0u8; SESSION_ID_LEN];
    OsRng.fill_bytes(&mut bytes);
    SessionId(bytes)
}

/// Derive `(host_to_client, client_to_host)` keys via HKDF-SHA256 keyed by the master secret,
/// salted with the session id.
pub fn derive_direction_keys(
    master: &MasterSecret,
    session_id: &SessionId,
) -> (DirectionKey, DirectionKey) {
    let hk = Hkdf::<Sha256>::new(Some(session_id.as_bytes()), master.as_bytes());
    let mut h2c = [0u8; KEY_LEN];
    let mut c2h = [0u8; KEY_LEN];
    // HKDF-Expand cannot fail for a 32-byte OKM with SHA-256.
    hk.expand(INFO_HOST_TO_CLIENT, &mut h2c)
        .expect("hkdf expand h2c");
    hk.expand(INFO_CLIENT_TO_HOST, &mut c2h)
        .expect("hkdf expand c2h");
    let keys = (DirectionKey(h2c), DirectionKey(c2h));
    // The `DirectionKey`s own zeroizing copies; wipe the `Copy` stack arrays we just made.
    h2c.zeroize();
    c2h.zeroize();
    keys
}

/// Compute the 6-digit SAS that both devices display for the user to compare.
///
/// Per the wire-format: take the first 4 bytes of `HMAC-SHA256(master, "flow-sync/1 sas"
/// ∥ session_id)`, **mask the top bit of byte 0** to a non-negative 31-bit big-endian integer, then
/// `mod 1_000_000`, zero-padded to 6 digits. The mask is required for byte-exact agreement with the
/// JVM/Kotlin side (which has no unsigned 32-bit int).
pub fn compute_sas(master: &MasterSecret, session_id: &SessionId) -> String {
    // `Mac` and `KeyInit` both provide `new_from_slice`; qualify to the HMAC one.
    let mut mac =
        <HmacSha256 as Mac>::new_from_slice(master.as_bytes()).expect("hmac accepts any key len");
    mac.update(SAS_LABEL);
    mac.update(session_id.as_bytes());
    let tag = mac.finalize().into_bytes();
    let n = u32::from_be_bytes([tag[0] & 0x7F, tag[1], tag[2], tag[3]]) % 1_000_000;
    format!("{n:0width$}", width = SAS_DIGITS)
}

/// Short, non-secret fingerprints of the two directional keys for cross-platform diagnostics:
/// `(host->client, client->host)`, each the first 8 lowercase-hex chars of `SHA-256(key)`. Logging
/// these on both devices makes an HKDF mismatch (different salt/labels/IKM) obvious — equal SAS but
/// different fingerprints would be impossible if derivation matched. Never logs the keys themselves.
pub fn key_fingerprints(master: &MasterSecret, session_id: &SessionId) -> (String, String) {
    let (h2c, c2h) = derive_direction_keys(master, session_id);
    let fp = |k: &DirectionKey| {
        let digest = <Sha256 as sha2::Digest>::digest(&k.0);
        digest[..4]
            .iter()
            .map(|b| format!("{b:02x}"))
            .collect::<String>()
    };
    (fp(&h2c), fp(&c2h))
}

fn to_hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// The HKDF outputs as lowercase hex — `(prk, k_h2c, k_c2h)` — for the golden vectors and
/// cross-platform diagnostics. `prk` is the HKDF-Extract pseudorandom key (salt = session_id, IKM =
/// master); the two keys are the directional Expands. Lets both repos assert byte-identical
/// derivation. Never log these in production — they ARE the session keys.
pub fn derive_key_material_hex(
    master: &MasterSecret,
    session_id: &SessionId,
) -> (String, String, String) {
    let (prk, hk) = Hkdf::<Sha256>::extract(Some(session_id.as_bytes()), master.as_bytes());
    let mut h2c = [0u8; KEY_LEN];
    let mut c2h = [0u8; KEY_LEN];
    hk.expand(INFO_HOST_TO_CLIENT, &mut h2c)
        .expect("hkdf expand h2c");
    hk.expand(INFO_CLIENT_TO_HOST, &mut c2h)
        .expect("hkdf expand c2h");
    let out = (to_hex(&prk), to_hex(&h2c), to_hex(&c2h));
    h2c.zeroize();
    c2h.zeroize();
    out
}

/// Seal with an **explicit nonce** — for the fixed-nonce golden vectors ONLY (production uses a
/// fresh random nonce via [`SessionCipher::seal`]; reusing a nonce with a key is catastrophic).
/// `key` is a raw 32-byte directional key. Returns `nonce ∥ ciphertext ∥ tag`.
pub fn seal_with_nonce(
    key: &[u8; KEY_LEN],
    session_id: &SessionId,
    frame_type: u8,
    seq: u64,
    nonce: &[u8; NONCE_LEN],
    plaintext: &[u8],
) -> Result<Vec<u8>, CryptoError> {
    let cipher = Aes256Gcm::new_from_slice(key).map_err(|_| CryptoError::InvalidKey)?;
    let aad = build_aad(session_id, frame_type, seq);
    let ciphertext = cipher
        .encrypt(
            Nonce::from_slice(nonce),
            Payload {
                msg: plaintext,
                aad: &aad,
            },
        )
        .map_err(|_| CryptoError::AuthFailed)?;
    let mut out = Vec::with_capacity(NONCE_LEN + ciphertext.len());
    out.extend_from_slice(nonce);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

/// Open a wire frame given a raw 32-byte directional key — the inverse of [`seal_with_nonce`] for the
/// golden vectors (the nonce is read from the wire prefix).
pub fn open_with_key(
    key: &[u8; KEY_LEN],
    session_id: &SessionId,
    frame_type: u8,
    seq: u64,
    wire: &[u8],
) -> Result<Vec<u8>, CryptoError> {
    let aad = build_aad(session_id, frame_type, seq);
    open_with(&DirectionKey(*key), &aad, wire)
}

/// Build the additional-authenticated-data for a frame:
/// `version(1) ∥ session_id(16) ∥ frame_type(1) ∥ seq(8, big-endian)`.
pub fn build_aad(session_id: &SessionId, frame_type: u8, seq: u64) -> Vec<u8> {
    let mut aad = Vec::with_capacity(1 + SESSION_ID_LEN + 1 + 8);
    aad.push(PROTOCOL_VERSION);
    aad.extend_from_slice(session_id.as_bytes());
    aad.push(frame_type);
    aad.extend_from_slice(&seq.to_be_bytes());
    aad
}

/// Bundles both directional keys for a session and applies the role to pick send/receive keys.
pub struct SessionCipher {
    session_id: SessionId,
    send_key: DirectionKey,
    recv_key: DirectionKey,
}

impl SessionCipher {
    pub fn new(master: &MasterSecret, session_id: SessionId, role: Role) -> Self {
        let (h2c, c2h) = derive_direction_keys(master, &session_id);
        let (send_key, recv_key) = match role {
            Role::Host => (h2c, c2h),
            Role::Client => (c2h, h2c),
        };
        Self {
            session_id,
            send_key,
            recv_key,
        }
    }

    pub fn session_id(&self) -> &SessionId {
        &self.session_id
    }

    /// Seal a plaintext frame for sending. Returns `nonce(12) ∥ ciphertext ∥ tag(16)`.
    pub fn seal(&self, frame_type: u8, seq: u64, plaintext: &[u8]) -> Result<Vec<u8>, CryptoError> {
        let aad = build_aad(&self.session_id, frame_type, seq);
        seal_with(&self.send_key, &aad, plaintext)
    }

    /// Open a received wire frame. Fails ([`CryptoError::AuthFailed`]) on any tamper / wrong key /
    /// wrong AAD (mismatched frame_type or seq).
    pub fn open(&self, frame_type: u8, seq: u64, wire: &[u8]) -> Result<Vec<u8>, CryptoError> {
        let aad = build_aad(&self.session_id, frame_type, seq);
        open_with(&self.recv_key, &aad, wire)
    }
}

fn seal_with(key: &DirectionKey, aad: &[u8], plaintext: &[u8]) -> Result<Vec<u8>, CryptoError> {
    let cipher = key.cipher()?;
    let mut nonce_bytes = [0u8; NONCE_LEN];
    OsRng.fill_bytes(&mut nonce_bytes);
    let nonce = Nonce::from_slice(&nonce_bytes);

    let ciphertext = cipher
        .encrypt(
            nonce,
            Payload {
                msg: plaintext,
                aad,
            },
        )
        .map_err(|_| CryptoError::AuthFailed)?;

    let mut out = Vec::with_capacity(NONCE_LEN + ciphertext.len());
    out.extend_from_slice(&nonce_bytes);
    out.extend_from_slice(&ciphertext);
    Ok(out)
}

fn open_with(key: &DirectionKey, aad: &[u8], wire: &[u8]) -> Result<Vec<u8>, CryptoError> {
    let min = NONCE_LEN + TAG_LEN;
    if wire.len() < min {
        return Err(CryptoError::FrameTooShort(wire.len(), min));
    }
    let (nonce_bytes, ciphertext) = wire.split_at(NONCE_LEN);
    let cipher = key.cipher()?;
    let nonce = Nonce::from_slice(nonce_bytes);
    cipher
        .decrypt(
            nonce,
            Payload {
                msg: ciphertext,
                aad,
            },
        )
        .map_err(|_| CryptoError::AuthFailed)
}

// Tests for this module live in `tests/sync_phase1.rs` (integration test) — see the note in
// `canonical.rs` on why in-crate unit tests can't run on this Tauri crate.
