export interface VideoSummary {
  id: string;
  title: string;
  channelName: string;
  channelId?: string | null;
  thumbnailUrl?: string | null;
  durationSeconds?: number | null;
  publishedText?: string | null;
  viewCountText?: string | null;
  channelAvatarUrl?: string | null;
  watchProgressPercent?: number | null;
  isLive?: boolean | null;
}

export interface RelatedContentItem {
  id: string;
  itemType: "video" | "playlist" | "mix" | string;
  title: string;
  channelName: string;
  channelId?: string | null;
  thumbnailUrl?: string | null;
  durationSeconds?: number | null;
  publishedText?: string | null;
  viewCountText?: string | null;
  videoId?: string | null;
  playlistId?: string | null;
  isMix: boolean;
  isLive?: boolean | null;
}

export interface VideoChapter {
  title: string;
  startSeconds: number;
  endSeconds: number;
}

export interface VideoDetails {
  id: string;
  title: string;
  channelName: string;
  channelId?: string | null;
  description?: string | null;
  thumbnailUrl?: string | null;
  durationSeconds?: number | null;
  likeCountText?: string | null;
  viewCountText?: string | null;
  publishedText?: string | null;
  chapters?: VideoChapter[];
  isLive?: boolean | null;
}

export interface StreamInfo {
  streamId: string;
  localUrl: string;
  expiresAt: string;
  variants: StreamVariant[];
  captions: CaptionTrack[];
  audioTracks: AudioTrack[];
  hlsManifestUrl?: string | null;
  dashManifestUrl?: string | null;
  isLive?: boolean | null;
  sabr?: SabrStreamInfo | null;
}

export interface LiveChatSegment {
  text: string;
  emojiImageUrl?: string | null;
}

export type LiveChatMessageType = "text" | "superChat" | "membership";

export interface LiveChatMessage {
  id: string;
  author: string;
  authorPhotoUrl?: string | null;
  message: string;
  segments: LiveChatSegment[];
  timestamp?: string | null;
  messageType: LiveChatMessageType;
  isOwner: boolean;
  isModerator: boolean;
  isVerified: boolean;
  isMember: boolean;
  memberBadgeUrl?: string | null;
  superChatAmount?: string | null;
  superChatArgb?: number | null;
  superChatHeaderArgb?: number | null;
}

export interface LiveChatResponse {
  messages: LiveChatMessage[];
  continuation?: string | null;
  pollingIntervalMs: number;
  isReplay: boolean;
}

/** SABR (Server Adaptive Bit Rate) availability + local manifest endpoint. */
export interface SabrStreamInfo {
  available: boolean;
  manifestUrl?: string | null;
  audioUrl?: string | null;
  videoUrl?: string | null;
  selectedAudioItag?: number | null;
  selectedVideoItag?: number | null;
  expiresInSeconds?: number | null;
  requiresPoToken: boolean;
  reasonUnavailable?: string | null;
}

export interface StreamVariant {
  id: string;
  localUrl: string;
  qualityLabel: string;
  mimeType?: string | null;
  width?: number | null;
  height?: number | null;
  fps?: number | null;
  bitrate?: number | null;
  isDefault: boolean;
  isPlayable: boolean;
  hasAudio: boolean;
  isVideoOnly: boolean;
  deliveryMethod: string;
  // Range metadata serialized by the backend (used to build synthetic DASH).
  initRangeStart?: number | null;
  initRangeEnd?: number | null;
  indexRangeStart?: number | null;
  indexRangeEnd?: number | null;
  approxDurationMs?: number | null;
}

export interface CaptionTrack {
  id: string;
  label: string;
  languageCode: string;
  url: string;
  isAutoGenerated: boolean;
}

export interface AudioTrack {
  id: string;
  label: string;
  languageCode?: string | null;
  audioTrackType?: string | null;
  localUrl: string;
  mimeType?: string | null;
  bitrate?: number | null;
  isDefault: boolean;
  /** Whether this track has a playable direct URL. Only the original track is offered, so this is always true. */
  available: boolean;
  initRangeStart?: number | null;
  initRangeEnd?: number | null;
  indexRangeStart?: number | null;
  indexRangeEnd?: number | null;
  approxDurationMs?: number | null;
}

export interface SearchVideosRequest {
  query: string;
  pageToken?: string | null;
  /** Server-side Innertube sort order. Omit/`relevance` for default. */
  sortBy?: "relevance" | "date" | "views" | "rating" | null;
  /** Server-side upload-date window. Omit/`any` for no filter. */
  uploadDate?: "any" | "hour" | "today" | "week" | "month" | "year" | null;
  /** Server-side duration bucket. Omit/`any` for no filter. */
  duration?: "any" | "short" | "medium" | "long" | null;
  /** Server-side boolean feature filter (e.g. `live`, `4k`, `hd`). */
  feature?:
    | "live"
    | "4k"
    | "hd"
    | "subtitles"
    | "creative_commons"
    | "360"
    | "hdr"
    | "vr180"
    | "location"
    | null;
}

export interface SearchVideosResponse {
  items: VideoSummary[];
  nextPageToken?: string | null;
  source: string;
}

export interface ChannelDetails {
  id: string;
  name: string;
  description?: string | null;
  avatarUrl?: string | null;
  bannerUrl?: string | null;
  subscriberCount?: number | null;
  subscriberCountText?: string | null;
  verified: boolean;
  availableTabs?: string[];
}

export interface ShortVideoSummary {
  type: "short";
  id: string;
  title: string;
  thumbnailUrl?: string | null;
  viewCountText?: string | null;
}

export interface PlaylistSummary {
  type: "playlist";
  id: string;
  title: string;
  thumbnailUrl?: string | null;
  videoCountText?: string | null;
}

export interface PostSummary {
  type: "post";
  id: string;
  authorName: string;
  authorAvatar?: string | null;
  textContent?: string | null;
  imageAttachment?: string | null;
  likesCountText?: string | null;
  publishedTimeText?: string | null;
}

export interface VideoItemSummary extends VideoSummary {
  type: "video";
}

export type ChannelItem = VideoItemSummary | ShortVideoSummary | PlaylistSummary | PostSummary;

export interface ChannelTabResponse {
  channelId: string;
  items: ChannelItem[];
  nextPageToken?: string | null;
  sortLatestToken?: string | null;
  sortPopularToken?: string | null;
  sortOldestToken?: string | null;
}

export interface PlaylistDetailsResponse {
  id: string;
  title: string;
  description?: string | null;
  channelName: string;
  videoCount?: number | null;
  viewCountText?: string | null;
  videos: VideoSummary[];
  nextPageToken?: string | null;
}

export interface Comment {
  id: string;
  author: string;
  authorThumbnail?: string | null;
  authorChannelId?: string | null;
  text: string;
  publishedText?: string | null;
  likeCount?: number | null;
  replyCount?: number | null;
  continuationToken?: string | null;
}

export interface CommentsResponse {
  comments: Comment[];
  nextPageToken?: string | null;
  commentCountText?: string | null;
}
