import React, { useEffect, useRef, useState } from "react";
import { X, Repeat, Share2, Play, Loader2 } from "lucide-react";
import { usePlayerStore } from "../../store/usePlayerStore";
import { useUiStore } from "../../store/useUiStore";
import type { VideoChapter, CaptionTrack } from "../../types/video";
import { invokeBackend } from "../../lib/api/errors";
import { parseCaptionCues, type CaptionCue } from "./SubtitleOverlay";
import { Select } from "../ui/Select";

interface ChaptersProps {
  chapters: VideoChapter[];
  captions?: CaptionTrack[];
  videoId?: string;
  onClose: () => void;
  videoThumbnail?: string;
  seekTo: (time: number) => void;
}

function formatTime(value: number) {
  if (!Number.isFinite(value) || value < 0) return "0:00";
  const total = Math.floor(value);
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const seconds = total % 60;

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, "0")}:${seconds
      .toString()
      .padStart(2, "0")}`;
  }
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

export const Chapters: React.FC<ChaptersProps> = ({
  chapters = [],
  captions = [],
  videoId,
  onClose,
  videoThumbnail,
  seekTo,
}) => {
  const currentTime = usePlayerStore((state) => state.currentTime);
  const showToast = useUiStore((state) => state.showToast);
  const containerRef = useRef<HTMLDivElement>(null);

  // Tabs state
  const [activeTab, setActiveTab] = useState<"chapters" | "transcript">("chapters");
  const [selectedCaptionId, setSelectedCaptionId] = useState<string>("off");
  const [transcriptCues, setTranscriptCues] = useState<CaptionCue[]>([]);
  const [loadingTranscript, setLoadingTranscript] = useState(false);
  const [transcriptError, setTranscriptError] = useState<string | null>(null);

  const activeChapter = chapters.find(
    (c) => currentTime >= c.startSeconds && currentTime <= c.endSeconds
  );

  // Set default tab based on whether there are chapters
  useEffect(() => {
    if (chapters && chapters.length > 0) {
      setActiveTab("chapters");
    } else {
      setActiveTab("transcript");
    }
  }, [chapters, videoId]);

  // Set default caption track
  useEffect(() => {
    if (captions && captions.length > 0) {
      const englishTrack = captions.find(c => c.languageCode === "en" && !c.isAutoGenerated)
        || captions.find(c => c.languageCode === "en")
        || captions[0];
      setSelectedCaptionId(englishTrack?.id || "off");
    } else {
      setSelectedCaptionId("off");
    }
  }, [captions, videoId]);

  // Fetch and parse subtitles for transcript tab
  useEffect(() => {
    if (activeTab !== "transcript" || selectedCaptionId === "off" || !captions || captions.length === 0) {
      setTranscriptCues([]);
      return;
    }

    const caption = captions.find((item) => item.id === selectedCaptionId);
    if (!caption) {
      setTranscriptCues([]);
      return;
    }

    setLoadingTranscript(true);
    setTranscriptError(null);
    let cancelled = false;

    invokeBackend<string>("fetch_subtitles", { url: caption.url })
      .then((text) => {
        if (cancelled) return;
        const cues = parseCaptionCues(text, !!caption.isAutoGenerated);
        setTranscriptCues(cues);
        setLoadingTranscript(false);
      })
      .catch((err) => {
        console.error("[Chapters/Transcript] Error fetching subtitles:", err);
        if (!cancelled) {
          setTranscriptError("Failed to load transcript.");
          setLoadingTranscript(false);
          setTranscriptCues([]);
        }
      });

    return () => {
      cancelled = true;
    };
  }, [activeTab, selectedCaptionId, captions, videoId]);

  const scrollActiveIntoView = (behavior: ScrollBehavior = "smooth") => {
    const activeEl = containerRef.current?.querySelector('[data-active="true"]');
    if (activeEl) {
      activeEl.scrollIntoView({ behavior, block: "center" });
    }
  };

  // Scroll active chapter/cue into view on initial activation or tab change
  useEffect(() => {
    const timer = setTimeout(() => {
      scrollActiveIntoView("smooth");
    }, 250);
    return () => clearTimeout(timer);
  }, [activeChapter?.startSeconds, activeTab]);

  const handleShare = (event: React.MouseEvent, chapter: VideoChapter) => {
    event.stopPropagation();
    try {
      const shareUrl = new URL(window.location.href);
      shareUrl.searchParams.set("t", Math.floor(chapter.startSeconds).toString());
      void navigator.clipboard.writeText(shareUrl.toString());
      showToast({
        variant: "success",
        message: `Copied link at ${formatTime(chapter.startSeconds)}.`,
      });
    } catch (err) {
      console.error("Failed to copy link", err);
      showToast({
        variant: "error",
        message: "Could not copy chapter link.",
      });
    }
  };

  const handleLoop = (event: React.MouseEvent, chapter: VideoChapter) => {
    event.stopPropagation();
    seekTo(chapter.startSeconds);
    showToast({
      variant: "info",
      message: `Looping chapter: ${chapter.title}`,
    });
  };

  return (
    <div className="flex h-full w-full flex-col bg-surface border border-white/15 rounded-xl text-white shadow-2xl relative overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/5 px-4 py-3.5 shrink-0">
        <h2 className="text-base font-bold tracking-tight text-zinc-100 flex items-center gap-2">
          In this video
        </h2>
        <button
          type="button"
          onClick={onClose}
          className="grid h-8 w-8 place-items-center rounded-full text-zinc-400 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
        >
          <X size={18} />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-white/5 px-4 gap-4 shrink-0 bg-background/20">
        <button
          type="button"
          onClick={() => chapters.length > 0 && setActiveTab("chapters")}
          className={`py-2.5 px-1 border-b-2 text-sm font-bold transition-all cursor-pointer ${
            activeTab === "chapters"
              ? "border-white text-white"
              : chapters.length > 0
              ? "border-transparent text-zinc-400 hover:text-zinc-200"
              : "border-transparent text-zinc-600 cursor-not-allowed"
          }`}
        >
          Chapters
        </button>
        <button
          type="button"
          onClick={() => captions && captions.length > 0 && setActiveTab("transcript")}
          className={`py-2.5 px-1 border-b-2 text-sm font-bold transition-all cursor-pointer ${
            activeTab === "transcript"
              ? "border-white text-white"
              : captions && captions.length > 0
              ? "border-transparent text-zinc-400 hover:text-zinc-200"
              : "border-transparent text-zinc-600 cursor-not-allowed"
          }`}
        >
          Transcript
        </button>
      </div>

      {/* List Container */}
      <div className="relative flex-1 min-h-0 flex flex-col">
        {/* Transcript Language Selector */}
        {activeTab === "transcript" && captions && captions.length > 1 && (
          <div className="px-4 py-2 border-b border-white/5 bg-white/5 flex items-center justify-between shrink-0">
            <span className="text-xs font-semibold text-zinc-400">Language</span>
            <Select
              value={selectedCaptionId}
              onChange={setSelectedCaptionId}
              options={captions.map((track) => ({
                value: track.id,
                label: `${track.label} ${track.isAutoGenerated ? "(auto)" : ""}`,
              }))}
            />
          </div>
        )}

        <div
          ref={containerRef}
          className="flex-1 overflow-y-auto px-3 py-3 select-scrollbar-hidden pb-20 custom-scrollbar"
        >
          {activeTab === "chapters" ? (
            <div className="space-y-2.5">
              {chapters.map((chapter, idx) => {
                const isActive = activeChapter
                  ? activeChapter.startSeconds === chapter.startSeconds
                  : false;

                return (
                  <div
                    key={`chapter-item-${idx}`}
                    data-active={isActive ? "true" : "false"}
                    onClick={() => seekTo(chapter.startSeconds)}
                    className={`group flex items-center gap-3.5 p-2 rounded-lg cursor-pointer transition-all duration-200 ${
                      isActive
                        ? "bg-white/10 border border-white/10 shadow-lg"
                        : "hover:bg-white/5 border border-transparent"
                    }`}
                  >
                    {/* Thumbnail card */}
                    <div className="relative w-28 aspect-video rounded-md overflow-hidden bg-zinc-900 border border-white/5 shadow shrink-0">
                      {videoThumbnail ? (
                        <img
                          src={videoThumbnail}
                          alt={chapter.title}
                          className="w-full h-full object-cover"
                        />
                      ) : (
                        <div className="w-full h-full flex items-center justify-center bg-zinc-950 font-bold text-zinc-700 text-xs">
                          FLOW
                        </div>
                      )}

                      {/* Play Overlay */}
                      <div className={`absolute inset-0 bg-black/40 flex items-center justify-center transition-opacity ${isActive ? "opacity-100" : "opacity-0 group-hover:opacity-100"}`}>
                        <Play size={20} className="text-white fill-white" />
                      </div>

                      {/* Red Time Badge */}
                      <span className="absolute bottom-1 right-1 bg-black/85 text-[10px] font-bold text-white px-1.5 py-0.5 rounded border border-white/5 font-mono">
                        {formatTime(chapter.startSeconds)}
                      </span>
                    </div>

                    {/* Info & Actions */}
                    <div className="flex-1 min-w-0 pr-1 flex flex-col justify-center">
                      <h4
                        className={`text-sm font-bold truncate transition-colors leading-tight ${
                          isActive ? "text-primary" : "text-zinc-100 group-hover:text-primary"
                        }`}
                      >
                        {chapter.title}
                      </h4>
                      <span className="text-xs font-semibold text-red-500 mt-1.5 font-mono">
                        {formatTime(chapter.startSeconds)}
                      </span>
                    </div>

                    {/* Side Actions (Loop & Share) */}
                    <div className="flex items-center gap-1.5 opacity-0 group-hover:opacity-100 transition-opacity shrink-0 pr-1">
                      <button
                        type="button"
                        title="Loop Chapter"
                        onClick={(e) => handleLoop(e, chapter)}
                        className="grid h-8 w-8 place-items-center rounded-full text-white/80 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
                      >
                        <Repeat size={20} />
                      </button>
                      <button
                        type="button"
                        title="Share Chapter Link"
                        onClick={(e) => handleShare(e, chapter)}
                        className="grid h-8 w-8 place-items-center rounded-full text-white/80 hover:bg-white/10 hover:text-white transition-colors cursor-pointer"
                      >
                        <Share2 size={20} />
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          ) : (
            <div className="space-y-3 px-1 pb-6">
              {loadingTranscript && (
                <div className="flex flex-col items-center justify-center py-16 text-zinc-500 gap-3">
                  <Loader2 className="animate-spin text-primary" size={24} />
                  <span className="text-xs font-semibold uppercase tracking-wider text-zinc-400">Loading transcript...</span>
                </div>
              )}
              {transcriptError && (
                <div className="text-center py-16 text-zinc-500 text-xs font-semibold uppercase tracking-wider">
                  {transcriptError}
                </div>
              )}
              {!loadingTranscript && !transcriptError && transcriptCues.length === 0 && (
                <div className="text-center py-16 text-zinc-500 text-xs font-semibold uppercase tracking-wider">
                  No transcript available.
                </div>
              )}
              {!loadingTranscript && !transcriptError && transcriptCues.map((cue, idx) => {
                const isCueActive = currentTime >= cue.start && currentTime <= cue.end;

                return (
                  <div
                    key={`transcript-cue-${idx}`}
                    data-active={isCueActive ? "true" : "false"}
                    onClick={() => seekTo(cue.start)}
                    className={`flex items-start gap-3.5 p-2 rounded-lg cursor-pointer transition-all duration-200 ${
                      isCueActive
                        ? "bg-white/10 border border-white/10 shadow-lg"
                        : "hover:bg-white/5 border border-transparent"
                    }`}
                  >
                    <span className="text-xs font-mono font-bold text-red-500 shrink-0 mt-0.5 min-w-[45px] hover:underline">
                      {formatTime(cue.start)}
                    </span>
                    <p className={`text-sm leading-relaxed transition-colors flex-1 ${
                      isCueActive ? "text-primary font-bold" : "text-zinc-200 font-medium"
                    }`}>
                      {cue.text}
                    </p>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Floating Sync Pill */}
        <div className="absolute bottom-4 left-1/2 -translate-x-1/2 z-10 shadow-xl rounded-full overflow-hidden">
          <button
            onClick={() => scrollActiveIntoView("smooth")}
            className="flex items-center gap-1.5 px-4 py-2 bg-white hover:bg-zinc-100 text-black font-bold text-xs rounded-full transition-all duration-150 cursor-pointer shadow-lg active:scale-95 whitespace-nowrap"
          >
            <Repeat size={12} className="rotate-180 text-black" />
            <span>Sync to video time</span>
          </button>
        </div>
      </div>
    </div>
  );
};

export default Chapters;
